version: '3.8'

services:
  naming-server:
    image: ayushchhipa01/naming-server:0.0.1-SNAPSHOT
    build:
      context: ./naming-server
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - currency-network

  api-gateway:
    image: ayushchhipa01/api-gateway:0.0.1-SNAPSHOT
    build:
      context: ./api-gateway
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    depends_on:
      - naming-server
    networks:
      - currency-network

  currency-exchange:
    image: ayushchhipa01/currency-exchange-service:0.0.1-SNAPSHOT
    build:
      context: ./currency-exchange-service
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    depends_on:
      - naming-server
    networks:
      - currency-network

  currency-conversion:
    image: ayushchhipa01/currency-conversion-service:0.0.1-SNAPSHOT
    build:
      context: ./currency-conversion-service
    ports:
      - "8100:8100"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    depends_on:
      - naming-server
      - currency-exchange
    networks:
      - currency-network

networks:
  currency-network:
    driver: bridge